### ISSUE TITLE
can the time/length of the track be added as part of the meta data collected?

### ISSUE THREAD

**Issue by jcastill0** [tmont/audio-metadata#2]

**Comment by tmont** [comment]
Yes, and in fact it already is for data with id3v2 frames (e.g. most mp3s). It'll be under the `TLEN` property in the result.

However, this value can't necessarily be trusted, since it's completely independent of the actual audio data. And decoding audio data is outside the scope of this library.

If you're trying to fetch track length in the browser, you can use the [`duration` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) from an `<audio>` element to get the actual length of the track.
